import type { Question } from './questionnaire.types'

export const questions: Question[] = [
  {
    id: 'edu_degree',
    category: 'education',
    type: 'single',
    text: 'What is your highest level of education?',
    textVi: 'Trình độ học vấn cao nhất của bạn?',
    options: [
      { value: 'high_school', label: 'High School', labelVi: 'Trung học phổ thông' },
      { value: 'associate', label: 'Associate Degree', labelVi: 'Cao đẳng' },
      { value: 'bachelor', label: 'Bachelor Degree', labelVi: 'Cử nhân' },
      { value: 'master', label: 'Master Degree', labelVi: 'Thạc sĩ' },
      { value: 'phd', label: 'PhD', labelVi: 'Tiến sĩ' },
    ],
    required: true,
    flowA: true,
    flowB: true,
  },
  {
    id: 'edu_major',
    category: 'education',
    type: 'text',
    text: 'What was your major or field of study?',
    textVi: 'Chuyên ngành học của bạn là gì?',
    required: true,
    flowA: true,
    flowB: true,
  },
  {
    id: 'exp_years',
    category: 'experience',
    type: 'single',
    text: 'How many years of professional experience do you have?',
    textVi: 'Bạn có bao nhiêu năm kinh nghiệm làm việc?',
    options: [
      { value: '0', label: 'No experience', labelVi: 'Chưa có kinh nghiệm' },
      { value: '0-1', label: 'Less than 1 year', labelVi: 'Dưới 1 năm' },
      { value: '1-3', label: '1-3 years', labelVi: '1-3 năm' },
      { value: '3-5', label: '3-5 years', labelVi: '3-5 năm' },
      { value: '5-10', label: '5-10 years', labelVi: '5-10 năm' },
      { value: '10+', label: 'More than 10 years', labelVi: 'Hơn 10 năm' },
    ],
    required: true,
    flowA: true,
    flowB: true,
  },
  {
    id: 'exp_industries',
    category: 'experience',
    type: 'multiple',
    text: 'Which industries have you worked in?',
    textVi: 'Bạn đã làm việc trong những ngành nào?',
    options: [
      { value: 'technology', label: 'Technology', labelVi: 'Công nghệ' },
      { value: 'finance', label: 'Finance', labelVi: 'Tài chính' },
      { value: 'healthcare', label: 'Healthcare', labelVi: 'Y tế' },
      { value: 'education', label: 'Education', labelVi: 'Giáo dục' },
      { value: 'retail', label: 'Retail', labelVi: 'Bán lẻ' },
      { value: 'manufacturing', label: 'Manufacturing', labelVi: 'Sản xuất' },
      { value: 'marketing', label: 'Marketing/Media', labelVi: 'Marketing/Truyền thông' },
      { value: 'consulting', label: 'Consulting', labelVi: 'Tư vấn' },
      { value: 'other', label: 'Other', labelVi: 'Khác' },
    ],
    required: false,
    flowA: true,
    flowB: false,
  },
  {
    id: 'skills_technical',
    category: 'skills',
    type: 'multiple',
    text: 'Which technical skills do you have?',
    textVi: 'Bạn có những kỹ năng kỹ thuật nào?',
    options: [
      { value: 'programming', label: 'Programming/Coding', labelVi: 'Lập trình' },
      { value: 'data_analysis', label: 'Data Analysis', labelVi: 'Phân tích dữ liệu' },
      { value: 'sql', label: 'SQL/Databases', labelVi: 'SQL/Cơ sở dữ liệu' },
      { value: 'excel', label: 'Excel/Spreadsheets', labelVi: 'Excel/Bảng tính' },
      { value: 'design', label: 'Design Tools', labelVi: 'Công cụ thiết kế' },
      { value: 'ai_tools', label: 'AI Tools', labelVi: 'Công cụ AI' },
      { value: 'none', label: 'None of the above', labelVi: 'Không có' },
    ],
    required: true,
    flowA: true,
    flowB: false,
  },
  {
    id: 'tools_used',
    category: 'tools',
    type: 'text',
    text: 'List the main tools and software you use regularly (e.g., Python, Figma, Tableau)',
    textVi: 'Liệt kê các công cụ và phần mềm bạn thường xuyên sử dụng (vd: Python, Figma, Tableau)',
    required: false,
    flowA: true,
    flowB: false,
  },
  {
    id: 'projects_completed',
    category: 'projects',
    type: 'single',
    text: 'How many substantial projects have you completed?',
    textVi: 'Bạn đã hoàn thành bao nhiêu dự án lớn?',
    options: [
      { value: '0', label: 'None', labelVi: 'Chưa có' },
      { value: '1-2', label: '1-2 projects', labelVi: '1-2 dự án' },
      { value: '3-5', label: '3-5 projects', labelVi: '3-5 dự án' },
      { value: '6-10', label: '6-10 projects', labelVi: '6-10 dự án' },
      { value: '10+', label: 'More than 10', labelVi: 'Hơn 10 dự án' },
    ],
    required: true,
    flowA: true,
    flowB: false,
  },
  {
    id: 'career_goals',
    category: 'careerMotivation',
    type: 'multiple',
    text: 'What are your primary career goals? (Select all that apply)',
    textVi: 'Mục tiêu nghề nghiệp chính của bạn là gì? (Chọn tất cả)',
    options: [
      {
        value: 'high_income',
        label: 'High income potential',
        labelVi: 'Thu nhập cao',
        preferenceSignal: { income: 90, growth: 75 },
      },
      {
        value: 'work_life_balance',
        label: 'Work-life balance',
        labelVi: 'Cân bằng công việc và cuộc sống',
        preferenceSignal: { stability: 80, remote: 70 },
      },
      {
        value: 'skill_growth',
        label: 'Continuous learning and skill development',
        labelVi: 'Học hỏi và phát triển kỹ năng liên tục',
        preferenceSignal: { growth: 90, autonomy: 70 },
        dimensionImpact: { learningAgility: 8, adaptability: 6 },
      },
      {
        value: 'social_impact',
        label: 'Making a positive social impact',
        labelVi: 'Tạo tác động xã hội tích cực',
        preferenceSignal: { socialImpact: 90 },
        dimensionImpact: { motivation: 8 },
      },
      {
        value: 'leadership',
        label: 'Leading teams and managing people',
        labelVi: 'Lãnh đạo đội nhóm và quản lý con người',
        dimensionImpact: { leadership: 10, communication: 6 },
      },
      {
        value: 'autonomy',
        label: 'Independence and autonomy',
        labelVi: 'Độc lập và tự chủ',
        preferenceSignal: { autonomy: 85, remote: 75 },
        workStyleSignal: ['builder', 'ambiguous'],
      },
    ],
    required: true,
    flowA: true,
    flowB: true,
  },
  {
    id: 'work_preference',
    category: 'workStyle',
    type: 'single',
    text: 'Which work environment do you prefer?',
    textVi: 'Bạn thích môi trường làm việc nào?',
    options: [
      {
        value: 'structured',
        label: 'Structured with clear processes',
        labelVi: 'Có cấu trúc và quy trình rõ ràng',
        workStyleSignal: ['structured'],
        preferenceSignal: { stability: 80 },
      },
      {
        value: 'flexible',
        label: 'Flexible and adaptable',
        labelVi: 'Linh hoạt và thích nghi',
        workStyleSignal: ['ambiguous'],
        dimensionImpact: { adaptability: 8 },
      },
      {
        value: 'collaborative',
        label: 'Highly collaborative',
        labelVi: 'Cộng tác cao',
        workStyleSignal: ['peopleFirst'],
        dimensionImpact: { collaboration: 10, communication: 6 },
      },
      {
        value: 'independent',
        label: 'Independent and focused',
        labelVi: 'Độc lập và tập trung',
        workStyleSignal: ['deepWork', 'builder'],
        preferenceSignal: { autonomy: 85 },
      },
    ],
    required: true,
    flowA: true,
    flowB: true,
  },
  {
    id: 'remote_preference',
    category: 'workStyle',
    type: 'scale',
    text: 'How important is remote work to you?',
    textVi: 'Làm việc từ xa quan trọng như thế nào với bạn?',
    scaleRange: { min: 0, max: 100, minLabel: 'Not important', maxLabel: 'Very important' },
    required: true,
    flowA: true,
    flowB: true,
  },
  {
    id: 'analytical_problem',
    category: 'analyticalThinking',
    type: 'single',
    text: 'When faced with a complex problem, you typically:',
    textVi: 'Khi đối mặt với vấn đề phức tạp, bạn thường:',
    options: [
      {
        value: 'break_down',
        label: 'Break it into smaller parts and analyze systematically',
        labelVi: 'Chia nhỏ và phân tích có hệ thống',
        dimensionImpact: { analyticalThinking: 12, logic: 8 },
      },
      {
        value: 'intuitive',
        label: 'Rely on intuition and past experience',
        labelVi: 'Dựa vào trực giác và kinh nghiệm',
        dimensionImpact: { creativity: 6, adaptability: 6 },
      },
      {
        value: 'discuss',
        label: 'Discuss with others to gain multiple perspectives',
        labelVi: 'Thảo luận với người khác để có nhiều góc nhìn',
        dimensionImpact: { communication: 10, collaboration: 10 },
      },
      {
        value: 'research',
        label: 'Research extensively before deciding',
        labelVi: 'Nghiên cứu kỹ lưỡng trước khi quyết định',
        dimensionImpact: { analyticalThinking: 8, learningAgility: 8 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'data_comfort',
    category: 'analyticalThinking',
    type: 'scale',
    text: 'How comfortable are you working with data and numbers?',
    textVi: 'Bạn tự tin đến mức nào khi làm việc với dữ liệu và con số?',
    scaleRange: { min: 0, max: 100, minLabel: 'Not comfortable', maxLabel: 'Very comfortable' },
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'creative_tasks',
    category: 'creativity',
    type: 'single',
    text: 'How do you approach creative tasks?',
    textVi: 'Bạn tiếp cận công việc sáng tạo như thế nào?',
    options: [
      {
        value: 'original',
        label: 'I enjoy generating completely original ideas',
        labelVi: 'Tôi thích tạo ra ý tưởng hoàn toàn mới',
        dimensionImpact: { creativity: 12, riskTolerance: 6 },
      },
      {
        value: 'improve',
        label: 'I prefer improving existing solutions',
        labelVi: 'Tôi thích cải tiến các giải pháp có sẵn',
        dimensionImpact: { analyticalThinking: 8, creativity: 4 },
      },
      {
        value: 'combine',
        label: 'I like combining ideas from different sources',
        labelVi: 'Tôi thích kết hợp ý tưởng từ nhiều nguồn',
        dimensionImpact: { creativity: 8, learningAgility: 6 },
      },
      {
        value: 'avoid',
        label: 'I prefer tasks with clear guidelines',
        labelVi: 'Tôi thích công việc có hướng dẫn rõ ràng',
        workStyleSignal: ['structured'],
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'communication_strength',
    category: 'communication',
    type: 'single',
    text: 'Which communication scenario do you excel at?',
    textVi: 'Bạn giỏi nhất trong tình huống giao tiếp nào?',
    options: [
      {
        value: 'presentation',
        label: 'Presenting to large groups',
        labelVi: 'Trình bày trước nhóm lớn',
        dimensionImpact: { communication: 12, leadership: 6 },
      },
      {
        value: 'writing',
        label: 'Written communication and documentation',
        labelVi: 'Giao tiếp bằng văn bản và tài liệu',
        dimensionImpact: { communication: 10, analyticalThinking: 4 },
      },
      {
        value: 'one_on_one',
        label: 'One-on-one conversations',
        labelVi: 'Trò chuyện một-một',
        dimensionImpact: { communication: 8, collaboration: 8 },
      },
      {
        value: 'technical',
        label: 'Explaining technical concepts simply',
        labelVi: 'Giải thích khái niệm kỹ thuật một cách đơn giản',
        dimensionImpact: { communication: 10, technicalAffinity: 6 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'team_role',
    category: 'leadership',
    type: 'single',
    text: 'In a team project, you naturally tend to:',
    textVi: 'Trong dự án nhóm, bạn thường có xu hướng:',
    options: [
      {
        value: 'lead',
        label: 'Take the lead and coordinate',
        labelVi: 'Đứng ra dẫn dắt và điều phối',
        dimensionImpact: { leadership: 12, decisionMaking: 8 },
      },
      {
        value: 'support',
        label: 'Support others and ensure smooth execution',
        labelVi: 'Hỗ trợ người khác và đảm bảo thực hiện mượt mà',
        dimensionImpact: { collaboration: 12, communication: 6 },
      },
      {
        value: 'execute',
        label: 'Focus on executing your assigned tasks well',
        labelVi: 'Tập trung thực hiện tốt nhiệm vụ được giao',
        workStyleSignal: ['deepWork', 'structured'],
      },
      {
        value: 'innovate',
        label: 'Propose new ideas and approaches',
        labelVi: 'Đề xuất ý tưởng và phương pháp mới',
        dimensionImpact: { creativity: 10, riskTolerance: 6 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'learning_speed',
    category: 'learningAgility',
    type: 'scale',
    text: 'How quickly do you typically learn new skills or concepts?',
    textVi: 'Bạn học kỹ năng hoặc khái niệm mới nhanh như thế nào?',
    scaleRange: { min: 0, max: 100, minLabel: 'Slowly, need time', maxLabel: 'Very quickly' },
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'tech_adoption',
    category: 'technicalAptitude',
    type: 'single',
    text: 'How do you feel about learning new technology?',
    textVi: 'Bạn cảm thấy thế nào về việc học công nghệ mới?',
    options: [
      {
        value: 'excited',
        label: 'Excited and eager to try new tools',
        labelVi: 'Hào hứng và muốn thử công cụ mới',
        dimensionImpact: { technicalAffinity: 12, learningAgility: 8 },
      },
      {
        value: 'practical',
        label: 'Open if it solves a real problem',
        labelVi: 'Sẵn sàng nếu nó giải quyết vấn đề thực tế',
        dimensionImpact: { technicalAffinity: 8, analyticalThinking: 6 },
      },
      {
        value: 'cautious',
        label: 'Prefer proven and stable technologies',
        labelVi: 'Thích công nghệ đã được chứng minh và ổn định',
        preferenceSignal: { stability: 80 },
        dimensionImpact: { technicalAffinity: 4 },
      },
      {
        value: 'avoid',
        label: 'Prefer to avoid highly technical work',
        labelVi: 'Thích tránh công việc có tính kỹ thuật cao',
        dimensionImpact: { technicalAffinity: -8 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'decision_style',
    category: 'decisionMaking',
    type: 'single',
    text: 'When making important decisions, you prefer to:',
    textVi: 'Khi đưa ra quyết định quan trọng, bạn thích:',
    options: [
      {
        value: 'data_driven',
        label: 'Rely on data and analysis',
        labelVi: 'Dựa vào dữ liệu và phân tích',
        dimensionImpact: { decisionMaking: 10, analyticalThinking: 8 },
      },
      {
        value: 'collaborative',
        label: 'Consult with others before deciding',
        labelVi: 'Tham khảo ý kiến người khác trước khi quyết định',
        dimensionImpact: { collaboration: 10, communication: 6 },
      },
      {
        value: 'quick',
        label: 'Make quick decisions and adjust as needed',
        labelVi: 'Quyết định nhanh và điều chỉnh theo tình hình',
        dimensionImpact: { decisionMaking: 8, adaptability: 8 },
      },
      {
        value: 'careful',
        label: 'Take time to consider all options carefully',
        labelVi: 'Dành thời gian cân nhắc kỹ tất cả phương án',
        dimensionImpact: { analyticalThinking: 8, riskTolerance: -4 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'risk_attitude',
    category: 'careerMotivation',
    type: 'single',
    text: 'How do you feel about career risks?',
    textVi: 'Bạn cảm thấy thế nào về rủi ro nghề nghiệp?',
    options: [
      {
        value: 'high_risk',
        label: 'Willing to take high risks for high rewards',
        labelVi: 'Sẵn sàng chấp nhận rủi ro cao để có phần thưởng lớn',
        dimensionImpact: { riskTolerance: 12 },
        preferenceSignal: { stability: 40, income: 85, autonomy: 80 },
      },
      {
        value: 'calculated',
        label: 'Take calculated risks after analysis',
        labelVi: 'Chấp nhận rủi ro có tính toán sau khi phân tích',
        dimensionImpact: { riskTolerance: 8, analyticalThinking: 6 },
      },
      {
        value: 'moderate',
        label: 'Balance stability and opportunity',
        labelVi: 'Cân bằng giữa ổn định và cơ hội',
        dimensionImpact: { riskTolerance: 4 },
        preferenceSignal: { stability: 65, growth: 70 },
      },
      {
        value: 'risk_averse',
        label: 'Prefer stable and predictable paths',
        labelVi: 'Thích con đường ổn định và dự đoán được',
        dimensionImpact: { riskTolerance: -4 },
        preferenceSignal: { stability: 90 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
  {
    id: 'motivation_driver',
    category: 'careerMotivation',
    type: 'single',
    text: 'What motivates you most in your work?',
    textVi: 'Điều gì thúc đẩy bạn nhiều nhất trong công việc?',
    options: [
      {
        value: 'achievement',
        label: 'Achieving goals and seeing results',
        labelVi: 'Đạt được mục tiêu và thấy kết quả',
        dimensionImpact: { motivation: 12, decisionMaking: 6 },
      },
      {
        value: 'mastery',
        label: 'Becoming an expert in my field',
        labelVi: 'Trở thành chuyên gia trong lĩnh vực',
        dimensionImpact: { motivation: 10, learningAgility: 8 },
      },
      {
        value: 'impact',
        label: 'Making a positive impact on others',
        labelVi: 'Tạo tác động tích cực đến người khác',
        dimensionImpact: { motivation: 10 },
        preferenceSignal: { socialImpact: 85 },
      },
      {
        value: 'recognition',
        label: 'Recognition and career advancement',
        labelVi: 'Được công nhận và thăng tiến',
        dimensionImpact: { leadership: 6, motivation: 8 },
      },
    ],
    required: true,
    flowA: false,
    flowB: true,
  },
]

export const getQuestionsByFlow = (flow: 'A' | 'B'): Question[] => {
  if (flow === 'A') {
    return questions.filter((q) => q.flowA)
  }
  return questions.filter((q) => q.flowB)
}
